rs1srv1:
    build: mongod
    command: "--replSet rs1 --noprealloc --smallfiles"
    ports:
    - "27017"

rs2srv1:
    build: mongod
    command: "--replSet rs2 --noprealloc --smallfiles"
    ports:
    - "27017"

cfg1:
    build: mongod
    command: "--noprealloc --smallfiles --configsvr --dbpath /data/db --port 27017"
    ports:
    - "27017"
    links:
    - rs2srv1:rs2srv1
    - rs1srv1:rs1srv1

#mongos1:
#    build: mongos
#    command: --port 27017 --configdb cfg1:27017
#    ports:
#    - "27017:27017"
#    links:
#    - cfg1:cfg1
