rs1srv1:
    build: mongod
    command: "--replSet rs1 --noprealloc --smallfiles"
    ports:
    - "27017"
    links:
    - ambassador:cfg1

rs2srv1:
    build: mongod
    command: "--replSet rs2 --noprealloc --smallfiles"
    ports:
    - "27017"
    links:
    - ambassador:cfg1

cfg1:
    build: mongod
    command: "--noprealloc --smallfiles --configsvr --dbpath /data/db --port 27017"
    ports:
    - "27017"
    links:
    - ambassador:rs2srv1
    - ambassador:rs1srv1

mongos1:
    build: mongos
    command: "--port 27017 --configdb cfg1:27017"
    ports:
    - "27017:27017"
    links:
    - ambassador:cfg1
    - ambassador:rs2srv1
    - ambassador:rs1srv1


ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
         - "/var/run/docker.sock:/docker.sock"
    name:
         - "rs1srv1"
         - "rs2srv1"
         - "cfg1"

#container1:
#    image: user/container1
#    ports:
#        - "8000:8000"
#    links:
#        - "ambassador:container1"
#
#container2:
#    image: user/container2
#    ports:
#        - "8080:8080"
#    links:
#        - "ambassador:container2"

